apiVersion: porter.sh/v1
kind: Installation
metadata:
  name: hello-2
  namespace: test
spec:
  schemaVersion: 1.0.2
  namespace: test
  name: kubernetes
  bundle:
    repository: ghcr.io/getporter/examples/kubernetes
    version: 0.2.0
  credentialSets:
    - porter-test-me
