# permissions for end users to view bundleinstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bundleinstallation-viewer-role
rules:
- apiGroups:
  - porter.sh
  resources:
  - bundleinstallations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porter.sh
  resources:
  - bundleinstallations/status
  verbs:
  - get
