name: build
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go run mage.go -v build deploy test
      - name: Set Docker Metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1 # crazy-max is, in fact, legit
        with:
          images: ghcr.io/getporter/porterops-controller
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/setup-buildx-action@v1 # build-push-action needs buildx installed
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
